server:
  port: 6071

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ec2-3-36-95-16.ap-northeast-2.compute.amazonaws.com:8761/eureka
  instance:
    instance-id: gateway-instance
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: web-service-route
          #uri: http://localhost:8080  # /web-service/**로 들어오면 http://localhost:8080 로 라우팅.
          uri: lb://web-service  # web-service로의 라우팅
          predicates:
            - Path=/web-service/**  # /web-service/**로 들어오는 uri는 web-service로 인식.

        - id: auth-service-route
          #uri: http://localhost:8081  # /auth-service/**로 들어오면 http://localhost:8081 로 라우팅.
          uri: lb://auth-service  # auth-service로의 라우팅
          predicates:
            - Path=/auth-service/**  # /auth-service/**로 들어오는 uri는 auth-service로 인식.
